### ISSUE TITLE
Send Bitcoin Payment information as E-Mail

### ISSUE THREAD

**Issue by Klar** [sanchaz/P2P-Electronic-Cash-Payments-for-WooCommerce#8]
I'm testing the plugin and its working well. What I'm missing is if a user buys something and chooses "Buy with Bitcoin SV" he will be redirected to a site where he can scan the QR code.

This is all good but if the user closes the site before paying, he is unable to access the payment information.

Would be cool to have a setting to send the Payment Information via E-Mail (I only found the manual admin send mail and without the bsv address). Maybe it's already there but I'm not seeing the configuration?

If you point me to the right direction I can try to implement this by myself.

Thanks in advance.

**Comment by sanchaz** [comment]
I haven't updated this or used it in a while.
Unless something has changed in WP/WC, then the user should always receive an email with the payment details (including a QR code) automatically.

**Comment by Klar** [comment]
There's an option for sending mails but only possible to send it manually, also when sending manually the bitcoin address / QR code information is missing.

**Comment by sanchaz** [comment]
I'm not sure if something has changed in woocommerce, but the "default_payment_instructions" used to get displayed and sent by email iirc.

It should be with this hook: woocommerce_email_before_order_table

https://github.com/sanchaz/P2P-Electronic-Cash-Payments-for-WooCommerce/blob/master/ecp-bitcoin-gateway.php#L67

**Comment by Klar** [comment]
seems to work now, not sure but probably an issue from my side with the code.
